{{ if eq .chezmoi.os "darwin" }}
[".hammerspoon/stackline"]
    type = "archive"
    url = "https://github.com/AdamWagner/stackline/archive/refs/heads/main.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".hammerspoon/Spoons/FocusHighlight.spoon"]
    type = "archive"
    url = "https://github.com/dtinth/FocusHighlight.spoon/archive/refs/tags/v0.1.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "2160h"
# https://github.com/Hammerspoon/Spoons/raw/master/Spoons/MouseFollowsFocus.spoon.zip
[".hammerspoon/Spoons/MouseFollowsFocus.spoon"]
    type = "archive"
    url = "https://github.com/Hammerspoon/Spoons/raw/master/Spoons/MouseFollowsFocus.spoon.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "2160h"
[".hammerspoon/Spoons/PaperWM.spoon"]
    type = "git-repo"
    url = "https://github.com/mogenson/PaperWM.spoon"
    exact = true
    refreshPeriod = "168h"
[".hammerspoon/Spoons/WarpMouse.spoon"]
    type = "git-repo"
    url = "https://github.com/mogenson/WarpMouse.spoon"
    exact = true
    refreshPeriod = "168h"
# ["Library/Keyboard Layouts/ColemakDHm.bundle"]
#     type = "archive"
#     url = "https://github.com/narze/Colemak-DHm/releases/download/stable/ColemakDHm.bundle.zip"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "2160h"
["Library/Keyboard Layouts/Manoonchai.bundle"]
    type = "archive"
    url = "https://github.com/narze/Manoonchai-ColemakDHm/releases/download/latest/Manoonchai.bundle.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "2160h"
{{ end -}}

[".tmux.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/narze/.tmux/master/.tmux.conf"
    refreshPeriod = "168h"
[".tmux.conf.local"]
    type = "file"
    url = "https://raw.githubusercontent.com/narze/.tmux/master/.tmux.conf.local"
    refreshPeriod = "168h"
[".config/zellij/plugins/zjstatus.wasm"]
    type = "file"
    url = "https://github.com/dj95/zjstatus/releases/download/v0.17.0/zjstatus.wasm"
    refreshPeriod = "168h"
[".config/zellij/plugins/zellij-autolock.wasm"]
    type = "file"
    url = "https://github.com/fresh2dev/zellij-autolock/releases/download/0.2.1/zellij-autolock.wasm"
    refreshPeriod = "168h"
[".local/share/git-worktree-runner"]
    type = "git-repo"
    url = "https://github.com/coderabbitai/git-worktree-runner.git"
    refreshPeriod = "48h"
